#!/bin/bash
bspc monitor -d I II III IV V VI
xsetroot -cursor_name left_ptr
xsetroot -solid "#0a0e14"
sxhkd &
polybar &
rxvt

bspc config border_width		1
bspc config window_gap			8

bspc config split_ratio			0.5
bspc config focus_follows_pointer	true
bspc config pointer_modifier		mod1
bspc config automatic_scheme		longest_side
